version: '3'
services:
  # airflow-create-user:
  #   image: apache/airflow:2.7.0
  #   environment:
  #     AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
  #   volumes:
  #     - ./airflow_conf/dags:/opt/airflow/dags
  #     - ./airflow_conf/logs:/opt/airflow/logs
  #     - ./airflow_conf/plugins:/opt/airflow/plugins
  #     - ./airflow_conf/airflow.db:/opt/airflow
  #   entrypoint: ["airflow", "users", "create"]
  #   command: >
  #     --username airflow
  #     --firstname airflow
  #     --lastname airflow
  #     --role Admin
  #     --email airflow
  #     --password airflow


  airflow-init:
    image: apache/airflow:2.7.0
    entrypoint: ["airflow", "db", "init"]
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow_conf/dags:/opt/airflow/dags
      - ./airflow_conf/logs:/opt/airflow/logs
      - ./airflow_conf/plugins:/opt/airflow/plugins
      - ./entrypoint.sh:/entrypoint.sh 
      - ./airflow_conf/airflow.db:/opt/airflow
      - ./data:/opt/airflow/dags/data
    
  webserver:
    image: apache/airflow:2.7.0
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      MONGO_URI: mongodb+srv://airflow:airflow@airflow.6pc0m.mongodb.net/miniprojet
    volumes:
      - ./airflow_conf/dags:/opt/airflow/dags
      - ./airflow_conf/logs:/opt/airflow/logs
      - ./airflow_conf/plugins:/opt/airflow/plugins
      - ./entrypoint.sh:/entrypoint.sh 
      - ./airflow_conf/airflow.db:/opt/airflow
      - ./data:/opt/airflow/dags/data
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
    # command: webserver
    command: >
      bash -c "pip install -r /requirements.txt && airflow webserver"

  scheduler:
    image: apache/airflow:2.7.0
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      MONGO_URI: mongodb+srv://airflow:airflow@airflow.6pc0m.mongodb.net/miniprojet
    volumes:
      - ./airflow_conf/dags:/opt/airflow/dags
      - ./airflow_conf/logs:/opt/airflow/logs
      - ./airflow_conf/plugins:/opt/airflow/plugins
      - ./entrypoint.sh:/entrypoint.sh 
      - ./airflow_conf/airflow.db:/opt/airflow
      - ./data:/opt/airflow/dags/data
      - ./requirements.txt:/requirements.txt
    depends_on:
      - webserver
      - airflow-init
    # command: scheduler
    command: >
      bash -c "pip install -r /requirements.txt && airflow scheduler"

  # react-dashboard:
  #   image: node:18
  #   working_dir: /app
  #   volumes:
  #     - ./react-dashboard:/app
  #   command: npm start
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     REACT_APP_MONGO_URI: mongodb+srv://airflow:airflow@airflow.6pc0m.mongodb.net/miniprojet

volumes:
  airflow_data: